name: Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  statuses: write

jobs:
  build:
    uses: neoforged/actions/.github/workflows/gradle-publish.yml@main
    with:
      java: 8
      gradle_tasks: 'publish'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}